# Generated by Django 5.2.13 on 2026-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Raw sentiment score (-1 to 1)', null=True),
        ),
    ]
