# Generated by Django 5.2.13 on 2026-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-updated_at'], name='news_newsar_updated_c12c93_idx'),
        ),
    ]
